.\" Manpage for citgm
.\" Contact jasnell@gmail.com to correct errors or typos
.TH "0.1.0" "MIT"
.SH NAME
citgm \- Canary in the Goldmine
.SH SYNOPSIS
citgm [options] <module>
.SH DESCRIPTION
citgm is a tool for testing Node.js modules against different Node.js builds.
Specifically, it automates the 'npm install' and 'npm test' steps and reports
back the status.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
output usage information
.TP
.BR \-V ", " \-\-version
output the version number
.TP
.BR \-v ", " \-\-verbose " " \fI[level]\fR
Verbose output (silly,verbose,info,warn,error)
.TP
.BR \-q ", " \-\-npm-loglevel " " \fI[level]\fR
Verbose output (silent, error, warn, http, info, verbose, silly)
.TP
.BR \-l ", " \-\-lookup " " \fI<path>\fR
Use the lookup table provided at <path>
.TP
.BR \-d ", " \-\-nodedir " " \fI<path>\fR
Path to the node source to use when compiling native addons
.TP
.BR \-n ", " \-\-no-color
Turns off colorized output
.TP
.BR \-s ", " \-\-su
Allow running the tool as root
.TP
.BR \-m ", " \-\-markdown
Output results in markdown
.TP
.BR \-t ", " \-\-tap " " \fI[path]\fR
Output results in tap
.TP
.BR \-u ", " \-\-uid " " \fIuid\fR
Set the uid (posix only)
.TP
.BR \-g ", " \-\-gid " " \fIuid\fR
Set the gid (posix only)
.SH EXAMPLES
Test the latest underscore module:

  citgm underscore@latest

Test a local module:

  citgm ./my-module

Test using a tar.gz from Github:

  citgm http://github.com/jasnell/activitystrea.ms/archive/master.tar.gz

.SH SEE ALSO
citgm-all
.SH AUTHOR
James M Snell <jasnell@gmail.com>
.SH COPYRIGHT
Copyright (c) 2015 citgm contributors
.SH LICENSE
The MIT License
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
