  env:
    node: true
    es6: true

  rules:
    indent: [2, 2]
    quotes: [2, single]
    no-trailing-spaces: 2
    comma-spacing: [2, { before: false, after: true }]
    eqeqeq: [2, always]
    linebreak-style: [2, unix]
    semi: [2, always]
    max-len: [2, 80]
    no-multi-spaces: 2
    no-useless-escape: 2
    array-bracket-spacing: [2, never]
    brace-style: 2
    capitalized-comments: 2
    eol-last: [2, always]
    func-call-spacing: [2, never]
    semi-spacing: 2
    strict: 2
    no-var: 2

  extends: eslint:recommended
