env:
  node: true
  es6: true
parserOptions:
  ecmaVersion: 2017

rules:
  eqeqeq: [error, always]
  no-useless-escape: error
  capitalized-comments: [error, always, { ignoreConsecutiveComments: true }]
  strict: error
  no-var: error
  prefer-template: error
  no-template-curly-in-string: error
  prefer-arrow-callback: error
  padding-line-between-statements:
    - error
    - { blankLine: always, prev: directive, next: '*' }
  # Rule is buggy: https://github.com/eslint/eslint/issues/11899
  require-atomic-updates: off

extends:
  - eslint:recommended
  - plugin:prettier/recommended
