env:
  node: true
  es6: true

rules:
  eqeqeq: [2, always]
  no-useless-escape: 2
  capitalized-comments: [2, always, { ignoreConsecutiveComments: true }]
  strict: 2
  no-var: 2
  prefer-template: 2
  no-template-curly-in-string: 2
  prefer-arrow-callback: 2

extends:
  - eslint:recommended
  - plugin:prettier/recommended
